version: '3.8'

services:
  auth-service:
    build: services/auth-service
    container_name: optiroute-auth
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://optiroute:optiroute123@postgres:5432/optiroute
    depends_on:
      - postgres
    networks:
      - optiroute-network

  postgres:
    image: postgres:15-alpine
    container_name: optiroute-db
    environment:
      POSTGRES_USER: optiroute
      POSTGRES_PASSWORD: optiroute123
      POSTGRES_DB: optiroute
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - optiroute-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: optiroute-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: optiroute
      RABBITMQ_DEFAULT_PASS: optiroute123
    networks:
      - optiroute-network

  upload-service:
    build:
      context: ./services/upload-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://optiroute:optiroute123@postgres:5432/optiroute
      RABBITMQ_URL: amqp://optiroute:optiroute123@rabbitmq:5672/
    volumes:
      - shared_uploads:/app/shared/uploads
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - optiroute-network

  optimization-service:
    build:
      context: ./services/optimization-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://optiroute:optiroute123@postgres:5432/optiroute
      RABBITMQ_URL: amqp://optiroute:optiroute123@rabbitmq:5672/
      TOMTOM_API_KEY: "19esvUIUdVPlPeqO7yNKqtlf481fncJT"
      REDIS_URL: redis://redis:6379
    volumes:
      - shared_uploads:/app/shared/uploads
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - optiroute-network

  results-service:
    build:
      context: ./services/results-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://optiroute:optiroute123@postgres:5432/optiroute
    depends_on:
      - postgres
    networks:
      - optiroute-network

  data-aggregator-service:
    build:
      context: ./services/data-aggregator-service
      dockerfile: Dockerfile
    environment:
      OPENWEATHERMAP_API_KEY: ""
      OPENAQ_API_KEY: ""
    networks:
      - optiroute-network

  redis:
    image: redis:7-alpine
    container_name: optiroute-redis
    ports:
      - "6379:6379"
    networks:
      - optiroute-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - optiroute-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - upload-service
      - results-service
      - data-aggregator-service
    networks:
      - optiroute-network

volumes:
  postgres_data:
  shared_uploads:
  auth_data:

networks:
  optiroute-network:
    driver: bridge